# Generated by Django 3.2 on 2023-02-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230214_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='user', null=True, verbose_name='О себе'),
        ),
    ]
