# Generated by Django 4.1.7 on 2023-02-15 13:27

from django.db import migrations, models
import django.db.models.deletion
import titles.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='название жанра')),
                ('slug', models.SlugField(unique=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('year', models.IntegerField(validators=[titles.validator.validate_year], verbose_name='год')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='описание')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='titles.category', verbose_name='категория')),
                ('genre', models.ManyToManyField(related_name='genres', to='titles.genre', verbose_name='жанр')),
            ],
            options={
                'verbose_name': 'название',
                'verbose_name_plural': 'названия',
                'ordering': ('-year',),
            },
        ),
    ]
